# Generated by Django 4.0.3 on 2022-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.CharField(max_length=125, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('location', models.CharField(max_length=264)),
                ('contact', models.CharField(max_length=264)),
            ],
        ),
    ]
